info:
  application:
    # read from pom.xml
    name: '@name@'
    description: '@description@'
    version: '@version@'
    build-time: '@maven.build.timestamp@'

spring:

  application:
    name: ${info.application.name}

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, heapdump, threaddump
  info:
    env:
      enabled: true
    java:
      enabled: true

google:
  cloud:
    api-key: ${GOOGLE_CLOUD_API_KEY}